### ISSUE TITLE
Is Remote / SSH or Remote / Container development supported?

### ISSUE THREAD

**Issue by tfenster** [microsoft/playwright-vscode#188]
Hello,

First of all, I really love Playwright, thanks a lot for this awesome extension!

As I try to do all development that I can remotely or in containers, I tried to set up the extension on a remote SSH Windows box (https://code.visualstudio.com/docs/remote/ssh). I can install the extension, trigger the playwright installation action and run headless tests without problems. However, if I try to e.g. set a breakpoint and debug the test, it just hangs when it gets to the breakpoint, I assume because it is trying to open a browser? Is that a supported scenario and I am doing something wrong or is running through remote/SSH not supported?

The same happens with Remote / Container with a WSL2 container on Windows. Same question here, am I missing something or is this not supported?

**Comment by mxschmitt** [comment]
> First of all, I really love Playwright, thanks a lot for this awesome extension!

Happy to hear!

Since debugging spawns a headful browser on the host OS, its not fully possible as of today due this contract.

> The same happens with Remote / Container with a WSL2 container on Windows. Same question here, am I missing something or is this not supported?

WSL2 support should be fixed in version 0.2.6 which was released a few minutes ago.

(There was a separate issue that the HTML report was not opening, this was an issue in Playwright, which you can fix by using the dev version: `npm install @playwright/test@next`.

**Comment by tfenster** [comment]
@mxschmitt Great news, thanks. However, when I try to do this now with a container and the updated extension, I get 
![image](https://user-images.githubusercontent.com/15346084/177596770-7dfec0ba-71c4-4f52-ae73-1105602b7709.png)
Do I need to do some setup / config on the Windows side for this to work?

**Comment by tfenster** [comment]
Ah sorry, I mixed up WSL and containers (cause Linux containers are also using WSL as backend on Windows, but obviously still not the same)

**Comment by ccll** [comment]
> In your scenario you are using containers, where debug is not supported. Why? Because when you debug, it will launch a headed browser, for that you need a GUI to see the browser and the playwright inspector, which you don't have in the container OR you can't control inside the container.

Is it possible to run headed browser with `xvfb` for rendering, and let user connect to the remote GUI with VNC to view/debug/control the tests?

It looks like Selenium docker container is doing headed rendering like this.
https://github.com/SeleniumHQ/docker-selenium

If this is possible in Playwright, it would be a huge improvement for remote development workflow.

**Comment by alexkuc** [comment]
@mxschmitt What if remote _supports headed mode, e.g. X11 forwarding? Would browser-related tasks work then?

**Comment by g1ronn1mo** [comment]
Any news?
